on:
  push:
    branches: [ main ]

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 生成镜像同步配置文件
      run: |
        echo "使用 GitHub Secrets 生成 config.json"
        sed -i 's|DOCKERHUB_PASSWORD|${{ secrets.DOCKERHUB_PASSWORD }}|g' configs/auth.json
        sed -i 's|DOCKERIO_PASSWORD|${{ secrets.DOCKERIO_PASSWORD }}|g' configs/auth.json
        sed -i 's|NVCRIO_PASSWORD|${{ secrets.NVCRIO_PASSWORD }}|g' configs/auth.json
        sed -i 's|GHCRIO_PASSWORD|${{ secrets.GHCRIO_PASSWORD }}|g' configs/auth.json
        sed -i 's|HARBOR_PASSWORD|${{ secrets.HARBOR_PASSWORD }}|g' configs/auth.json

    - name: 检查架构
      run: |
        tree  .

    - name: 执行同步镜像
      run: |
        set -e  # 如果有命令失败则停止执行
        echo "开始同步镜像"
        chmod +x image-syncer155/image-syncer 
        ./image-syncer155/image-syncer --proc=2 --auth=configs/auth.json --images=configs/images.json --retries=1 || { echo '镜像同步失败'; exit 1; }
        echo "同步镜像完成"

    - name: 通知钉钉机器人
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{
          "msgtype": "text",
          "text": {
            "content": "镜像同步任务完成！"
          }
        }' https://oapi.dingtalk.com/robot/send?access_token=8953afbe643682a206506b08d649e400c728c20a6eccf874553865d4d45a1a0a
