name: docker-image-sync

on:
  push:
    branches: [ main ]

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 镜像同步配置处理
      run: |
        echo "处理 auth.json 中的密码"
        sed -i 's|${{ secrets.DOCKERHUB_PASSWORD }}|'"${{ secrets.DOCKERHUB_PASSWORD }}"'|g' auth.json

    - name: 下载 image-syncer 工具包
      run: |
        echo "下载 image-syncer 工具包"
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/v1.5.5/image-syncer-v1.5.5-linux-amd64.tar.gz
        tar -zxf image-syncer-v1.5.5-linux-amd64.tar.gz

    - name: 执行同步镜像
      run: |
        set -e  # 如果有命令失败则停止执行
        echo "开始同步镜像"
        ./image-syncer --proc=3 --auth=auth.json --images=images.json --retries=1 || { echo '镜像同步失败'; exit 1; }
        echo "同步镜像完成"
