name: docker-image-sync

on:
  push:
    branches: [ main ]

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 生成镜像同步配置文件
      run: |
        echo "使用 GitHub Secrets 生成 config.json"
        sed -i 's|DOCKERHUB_PASSWORD|${{ secrets.DOCKERHUB_PASSWORD }}|g' configs/auth.json
        sed -i 's|DOCKERIO_PASSWORD|${{ secrets.DOCKERIO_PASSWORD }}|g' configs/auth.json
        sed -i 's|NVCRIO_PASSWORD|${{ secrets.NVCRIO_PASSWORD }}|g' configs/auth.json
        sed -i 's|GHCRIO_PASSWORD|${{ secrets.GHCRIO_PASSWORD }}|g' configs/auth.json

    - name: 检查当前架构
      run: |
        tree  .

    - name: 执行同步镜像
      run: |
        set -e  # 如果有命令失败则停止执行
        echo "开始同步镜像"
        chmod +x image-syncer155/image-syncer  # 赋予执行权限
        ./image-syncer155/image-syncer --proc=3 --auth=configs/auth.json --images=configs/images.json --retries=2 || { echo '镜像同步失败'; exit 1; }
        echo "同步镜像完成"
