name: docker-image-sync
on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: '0 01 * * *'
  
jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 镜像同步配置处理
      run: |
        echo "处理配置文件"
        # 将 DOCKERHUB_PASSWORD 直接替换为明文密码
        sed -i 's/DOCKERHUB_PASSWORD/NhyaP7dsmPEzEH8Qz0FW6Iq52rR9Kx/g' config.json

        
    - name: 下载image-sync工具包
      run: |
        echo "下载 image-syncer 工具包"
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/v1.5.5/image-syncer-v1.5.5-linux-amd64.tar.gz
        tar -zxf image-syncer-v1.5.5-linux-amd64.tar.gz

    - name: 查看解压后的文件
      run: |
        ls -l  # 查看解压目录中的文件，确保 image-syncer 存在

    - name: 确保文件有执行权限
      run: |
        chmod +x image-syncer  # 确保 image-syncer 有执行权限

    - name: 执行同步镜像
      id: sync
      run: |
        set -e  # 如果有命令失败则停止执行
        echo "开始同步镜像"
        ./image-syncer --proc=20 --config=config.json --retries=2 || { echo '镜像同步失败'; exit 1; }
        echo "同步镜像完成"
