name: docker-image-sync
on:
  push:
    branches: [ main ]
  #schedule:
  #  - cron: '0 01 * * *'

jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: 镜像同步配置处理
      run: |
        sed -i 's/DOCKERHUB_PASSWORD/${{ secrets.DOCKERHUB_PASSWORD }}/g' config.json
        
    - name: 下载image-sync工具包
      run: |
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/v1.5.5/image-syncer-v1.5.5-linux-amd64.tar.gz
        tar -zxf image-syncer-v1.5.5-linux-amd64.tar.gz
      
    - name: 创建镜像列表文件
      run: |
        # 生成镜像对的列表
        echo -e "docker.io/nginx:latest registry.cn-hangzhou.aliyuncs.com/imagessync/nginx" > images_list.txt
        echo -e "gcr.io/kaniko-project/executor registry.cn-hangzhou.aliyuncs.com/imagessync/kaniko-executor" >> images_list.txt

        # 输出镜像列表用于调试
        cat images_list.txt

    - name: 执行同步镜像
      id: sync
      run: |
        # 使用 --images 标志提供镜像列表文件
        ./image-syncer --proc=20 --images=images_list.txt --retries=2

    - name: 发送钉钉通知
      run: |
        STATUS="同步成功"
        if [[ "${{ steps.sync.outcome }}" == "failure" ]]; then
          STATUS="同步失败"
        elif [[ "${{ steps.sync.outcome }}" == "skipped" ]]; then
          STATUS="镜像已存在"
        fi

        # 发送钉钉通知
        curl -X POST https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.ACCESS_TOKEN }} \
        -H 'Content-Type: application/json' \
        -d "{
          \"msgtype\": \"text\",
          \"text\": {
            \"content\": \"同步状态: ${STATUS}\"
          },
          \"at\": {
            \"isAtAll\": true
          }
        }"
