name: docker-image-sync
on:
  push:
    branches: [ main ]
  
jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 生成镜像同步配置文件
      run: |
        echo "使用 GitHub Secrets 生成 config.json"
        sed -i 's|DOCKERHUB_PASSWORD|${{ secrets.DOCKERHUB_PASSWORD }}|g' config.json

    - name: 下载 image-sync 工具包
      run: |
        echo "下载 image-syncer 工具包"
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/v1.5.5/image-syncer-v1.5.5-linux-amd64.tar.gz
        tar -zxf image-syncer-v1.5.5-linux-amd64.tar.gz
      
        - name: 执行同步镜像
        id: sync
        run: |
          set -e  # 如果有命令失败则停止执行
          echo "开始同步镜像"
          ./image-syncer --proc=20 --config=config.json --retries=2 --log=/tmp/sync.log || { echo '镜像同步失败'; exit 1; }
          echo "同步镜像完成"
          cat /tmp/sync.log  # 输出日志内容，帮助排查错误
      
