name: docker-image-sync
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 01 * * *'
  
jobs:
  image-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: 镜像同步配置处理
      run: |
        echo "处理配置文件"
        sed -i 's/DOCKERHUB_PASSWORD/${{ secrets.DOCKERHUB_PASSWORD }}/g' config.json
        
    - name: 下载image-sync工具包
      run: |
        echo "下载 image-syncer 工具包"
        wget https://github.com/AliyunContainerService/image-syncer/releases/download/v1.3.1/image-syncer-v1.3.1-linux-amd64.tar.gz
        tar -zxf image-syncer-v1.3.1-linux-amd64.tar.gz
      
    - name: 执行同步镜像
      run: |
        set -e  # 如果有命令失败则停止执行
        echo "开始同步镜像"
        ./image-syncer --proc=20 --config=config.json --retries=2 || { echo '镜像同步失败'; exit 1; }
        echo "同步镜像完成"

    - name: 发送钉钉通知
      run: |
        STATUS="同步成功"
        if [[ "${{ steps.sync.outcome }}" == "failure" ]]; then
          STATUS="同步失败"
        elif [[ "${{ steps.sync.outcome }}" == "skipped" ]]; then
          STATUS="镜像已存在"
        fi

        # 发送钉钉通知
        curl -X POST https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.ACCESS_TOKEN }} \
        -H 'Content-Type: application/json' \
        -d "{
          \"msgtype\": \"text\",
          \"text\": {
            \"content\": \"同步状态: ${STATUS}\"
          },
          \"at\": {
            \"isAtAll\": true
          }
        }"
